ALTER TABLE session
ADD COLUMN IF NOT EXISTS regime TEXT;

ALTER TABLE session
ADD COLUMN IF NOT EXISTS core_spread DECIMAL(10,2);

ALTER TABLE session
ADD COLUMN IF NOT EXISTS provisional_count INTEGER;
